### ISSUE TITLE
Refactor sync.Mutex for workers/server

### ISSUE THREAD

**Issue by jsimnz** [pressly/qmd#22]
Been looking into using qmd for some job processing stuff, but I noticed some global mutex, that should be embedded into a `safe map` like structure.

In worker.go, the Worker struct has a Jobs map defined and its the only thing (seemingly) that uses the global mutex.

Should us a 'safe map' struct defined as follows

```
type safeJobMap struct {
    jobs map[string]*Job
    *sync.Mutex
}
```

and the worker should be

```
type Worker struct {
    ...
    Jobs safeJobMap
    ...
}
```

this also applies for the Server struct with the sMutex and the Requests object

**Comment by VojtechVitek** [comment]
https://github.com/pressly/qmd/pull/30
